### ISSUE TITLE
Fall 2017 Event - Preliminary Quality Review

### ISSUE THREAD

**Issue by dudleycodes** [LacledesLAN/gamesvr-csgo-freeplay#1]
- [x] Update MM / SM to latest
- [x] Make sure linux files are in `dist.linux` and that generic files are in `dist`
- [x] Verify advertisements works
- [x] Verify `sm_admin` works
- [x] Verify MOTD works
- [x] Verify your custom plugin is installed and working (dumps info to console on startup)
- [x] Verify LL config is loading
- [x] Verify fast downloads work
- [x] Verify map-voting works

**Comment by JustinBenedick** [comment]
updated sm/mm and sorted da5e6b8

**Comment by JustinBenedick** [comment]
Skipped MOTD
