### ISSUE TITLE
CSGO No longer has the operations maps by default

### ISSUE THREAD

**Issue by JustinBenedick** [LacledesLAN/gamesvr-csgo-freeplay#4]
In the past the extra CSGO operations maps have been included in the client and server, and could be ran just like stock maps with a custom playlist. As of 4/16 it was discovered that these maps are no longer included and thus for future events and somehow need to be loaded on to the docker image.  There are a few solutions that come to mind with their own pros and cons.

The list of maps can be found here
https://steamcommunity.com/sharedfiles/filedetails/?id=585652233
http://counterstrike.wikia.com/wiki/Map/List#Operations_maps

A couple of possibilities for a fix

1. Follow the recommendation from valve and put in the api key and collection id in the right files. However this would cause the server to auto download all maps on the start of every startup which would slow it down.  https://developer.valvesoftware.com/wiki/CSGO_Workshop_For_Server_Operators

2. Copy maps to the file server.  This would have all files on all csgo images just like the "orange" test maps. This could possibly balloon up the size of all csgo images by a gig or 2. Downside is that this could cause version issues with the client if the map gets out of date. Upside is that it would work without modification of any dockerfiles.

3. Somehow download via steam cmd. Its not fully fleshed out but initial tests show that workshop  maps can be download individually. Problems are that the command cannot use anonymous login (and steam guard comes into play), download files as a bin file (not known if its good for a server), and its one file at a time. If implemented correctly this could be implemented directly into the dockerfile. Low chance of this one.

**Comment by dudleycodes** [comment]
1) Sounds like a false start; as we move everything into Kubernetes it's vital that the images themselves are production-ready and start quickly.

2) While annoying ~2 GB large image wouldn't be an issue overall; just means longer downloads. Client/server versioning issues does sound like a big issue. @JustinBenedick is there anyway we could force game clients to download from the fast download server?

3) Sounds the most promising. @JustinBenedick - can you provide any example (don't include actual login in credentials)? Would the game clients still try to download these maps from the workshop?

**Comment by JustinBenedick** [comment]
!. If it possible to run the images in the cloud, and save the files before download to the server it would work.

2. sounds like something I would need to test. I am guessing it would differentiate from WS version and Sideload version. 

3. ~/gameserver/util/steamcmd/steamcmd.sh +login NAME PASS +force_install_dir /home/sysoper/workshopdown -api_key APIKEY +workshop_download_item 730 585652233 +quit

I am just not sure of file compatability yet.

**Comment by dudleycodes** [comment]
@JustinBenedick - please thoroughly test and prototype how we can download from the workshop, stage to file server / docker image, and then get the csgo game clients to download from our fast download server and *no* the workshop. I wonder if simply renaming the file(s) would be enough?

**Comment by dudleycodes** [comment]
Closing this issue now that @JustinBenedick's "compromise" map set is in place.
